export default async function help(args, shell) {
    const commands = [
        'ls [-la] [path]  - List directory contents',
        'cd [path]        - Change directory',
        'pwd              - Print working directory',
        'mkdir [path]     - Create directory',
        'touch [path]     - Create empty file',
        'rm [-r] [path]   - Remove file or directory',
        'mv [src] [dest]  - Move file or directory',
        'cp [-r] [s] [d]  - Copy file or directory',
        'chmod [mode] [f] - Change file permissions',
        'chown [owner] [f]- Change file owner',
        'cat [file]       - Display file content',
        'nano [file]      - Open Nano text editor',
        'vim [file]       - Open Vim modal text editor',
        'head [-n X] [f]  - Display first X lines',
        'tail [-n X] [f]  - Display last X lines',
        'wc [-lwc] [file] - Word, line, and character count',
        'grep [-vin] [p]  - Search text for pattern',
        'find [path]      - Search for files',
        'sudo [command]   - Execute command as root',
        'ps               - List processes',
        'top              - System monitor snapshot',
        'who              - List logged in users',
        'fetch            - Display system information summary',
        'matrix           - Start digital rain animation (Esc to exit)',
        'sh [file]        - Execute shell script',
        'ping [host]      - Test network connectivity (simulated)',
        'curl [url]       - Transfer data from a URL (simulated)',
        'theme [name]     - Change terminal theme (matrix, ubuntu, retro, classic, nord, monokai)',
        'snake            - Play a game of Snake (Arrow keys to move, Esc to exit)',
        'echo [text]      - Print text',
        'write [file] [c] - Write content to file',
        'append [file] [c]- Append content to file',
        'export [K=V]     - Set environment variable',
        'alias [n=c]      - Set command alias',
        'history [-c]     - Show or clear command history',
        'env              - List environment variables',
        'clear            - Clear terminal screen',
        'reset            - Reset all terminal data',
        'whoami           - Show current user',
        'date             - Show current date/time',
        'uptime           - Show system uptime',
        'uname [-a]       - Show system information',
        'exit             - Close terminal session'
    ];
    
    return 'Consoul Terminal - Available Commands:\n\n' + commands.join('\n');
}
